### ISSUE TITLE
[a11y tool] exporer stops at collapsed subexpression

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#108]
I can't explore beyond it (neither horizontally or vertically).

**Comment by zorkow** [comment]
Which version of SRE are you using? MathJax-accessibility?

**Comment by pkra** [comment]
> Which version of SRE are you using? MathJax-accessibility?

I was using https://github.com/mathjax/MathJax-RespEq/blob/master/examples/Struik-speech.html (via rawgit.com)

**Comment by pkra** [comment]
I don't see the issue on http://codepen.io/pkra/pen/yOWrWQ so I'm guessing I was either using an outdated version or it was fixed.
