### ISSUE TITLE
[a11y extension] question on line-breaking

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#111]
More an note to self since I can't test right now. 

Does the extension disable line-breaking?

**Comment by pkra** [comment]
Clarify: does the auto-collapse mode disable line-breaking?

**Comment by dpvc** [comment]
It doesn't disable it, but it probably don't interact well with it.  I haven't tested that.

**Comment by pkra** [comment]
> It doesn't disable it, but it probably don't interact well with it. I haven't tested that.

Copy that. 

I imagine the situation where I open a page, the line-breaking is poor and I want to switch on the collapsing to get a better experience.

I just tried this with struik. The result is that collapsing works but the line-breaks will not be "undone". That's ok for now, I think (and linebreaks will improve after all) but I wonder if line-breaking shouldn't be user-configurable. But that's an upstream topic, I suppose.
