### ISSUE TITLE
Assistive-Explorer.js explorer or walker?

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#115]
We sometimes call it walker, sometimes explorer. Should these be identical? If so, we should decide on a unique name.

**Comment by pkra** [comment]
In particular, the extension is called Explorer but the relevant option is walker.

Since the extension provides much more, perhaps it should be named differently.

**Comment by dpvc** [comment]
Actually, the extension is called "Explore" not "Explorer", though I think the latter is better.  I prefer "Explorer" to "Walker", but am not adamant about it.

**Comment by pkra** [comment]
As per my own suggestion at https://github.com/mathjax/MathJax-RespEq/issues/117#issuecomment-222609025, I created https://github.com/mathjax/MathJax-RespEq/wiki/Harmonizing-naming

**Comment by dpvc** [comment]
Thanks.  That should be a good basis for discussion on our next call.
