### ISSUE TITLE
Accessibility-Extension.js naming

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#116]
I was wondering about the name. -Extensions (plural) seems a bit more fitting (but might lead to typos). Something like Accessibility-Loader / a11y-loader is more fitting but perhaps not as easy to remember. Not a huge thing but wanted to raise it (esp in the context of #115)

**Comment by dpvc** [comment]
I also wondered about the name.  I thought "Accessibility-Menu" might be better, since this one really is about adding the menu items for people to opt into the extensions, and that is the visual effect of loading this extension.

**Comment by pkra** [comment]
>  I thought "Accessibility-Menu" might be better,

Very good point. I liked just `a11y` (cf [wiki](https://github.com/mathjax/MathJax-RespEq/wiki/Harmonizing-naming))  but your idea is more sensible.

**Comment by pkra** [comment]
Closing in favor of #118
