### ISSUE TITLE
Moar demos

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#28]
Just to record this from other conversations. It would be good to revive the older demos that only show some features, e.g.,

* just enrichment (right now, the demos add mactions for collapsing), e.g., http://codepen.io/pkra/pen/oXLGZQ
* just collapsing (no speech text or walker)

**Comment by zorkow** [comment]
No speech or walker should not be a problem. Just leave out the Assistive-Explore code.
You will also have to leave out the configuration for the Explorer.

**Comment by pkra** [comment]
closing in favor of #44
