### ISSUE TITLE
Don't collapse endpunct and startpunct

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-RespEq#3]
Punctuated with role endpunct or startpunct should not be collapsed.
These are expressions that contain a single punctuation at start or end, only. In most maths expressions this is irrelevant. 
For example:
a = b.
will lead to 
<.>
Instead it should lead to 
<=>.

**Comment by dpvc** [comment]
Thanks, I'll take care of it.

Is there a list of all the types and their possible roles anywhere?  So far, I've been going purely by experimentation, but it would be great to do it by an exhaustive list.

**Comment by zorkow** [comment]
Most is given in the still incomplete grammar document. All the types are there. The roles are still terribly incomplete. I'll do those next, as they will become more important now, as this example shows.

**Comment by dpvc** [comment]
This is fixed in commit 710c9f7.
