### ISSUE TITLE
SVG maction class name

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-RespEq#32]
@dpvc 
I would have expected the collapsible elements in SVG to have class mjx-svg-maction.
However, they have no classname at all, so hover and flame do not work.

**Comment by dpvc** [comment]
Remember that by default the SVG output doesn't preserve the MathML structure (it collapses groups to reduce the complexity of the output).  So it may remove the SVG elements that correspond to the individual MathML elements.  If you want to have the structure preserved in SVG output, you need to set `addMMLclasses` to true in the SVG configuration block.  Then you will have the elements marked by class names like `mjx-svg-maction`, and the group structure will reflect the MathML tree.

**Comment by pkra** [comment]
This can be closed?

**Comment by dpvc** [comment]
I think so.  Pull 33 should have resolved the issue.
