### ISSUE TITLE
Enriched Math Tex Error

### ISSUE THREAD

**Issue by SamBevan1994** [mathjax/MathJax-RespEq#34]
When entering a formula including something similar to:
( x + 1 ) ^2 =
The exponent is applied to the last term within the brackets, rather than the brackets as a hole.

(I've attached a screenshot to demonstrate)
![screenshot1](https://cloud.githubusercontent.com/assets/15610840/11301235/6200e66c-8f8d-11e5-848b-7d416880fe3f.png)

**Comment by pkra** [comment]
Thanks so much for reporting this here.

**Comment by zorkow** [comment]
Fixed in SRE.
