### ISSUE TITLE
[a11y tool] JAWS adds "blank" in front of each speech string

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#40]
JAWS voices "blank" before each speech string during exploration. 

However, it usually stops doing that after a while and start voicing things correctly. 

I have not been able to figure out how to trigger this change in behavior. It might be a bug in JAWS or it might be something we can tweak. Let's reach out.

**Comment by pkra** [comment]
I just had a case where JAWS started out without "blank" (on Chrome) but then switched to it  (as I switched to Firefox) and kept that when switching back to Chrome. No idea what's going on...

**Comment by pkra** [comment]
This seems to happen a lot less when I open just one browser at a time.

**Comment by pkra** [comment]
According to Freedom Scientific, this is caused by clashes with their own math solution. That would make it unfixable on our end.

**Comment by zorkow** [comment]
Is there anything we can and should do? Find a work around for the Jaws problem?

**Comment by pkra** [comment]
I have not encountered this while testing #52 so I'm guessing the changed role fixes this.
