### ISSUE TITLE
Sample with processing error 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#43]
The sample from our MathUI paper is throwing an error in the Semantics-Lab (but not in regular MathJax).

```latex
\begin{align*}
I_\nu(\nu^{-1},1)
&=\underbrace{\frac{\pi^2}{4}\ln\left(\frac{(1+\nu)^{1+\nu}}{\nu^\nu}
\right)-\frac{7\zeta(3)}{8}\nu}_{\text{Let this be
C}}+2\int^\frac{1-\nu}{1+\nu}_1\frac{\chi_3(v)}{(1+v)^2}{\rm d}v\\
&=C-\left.\frac{2\chi_3(v)}{1+v}\right|^\frac{1-\nu}{1+\nu}_1+2\int^\frac{1-\nu}
{1+\nu}_1\frac{\chi_2(v)}{v(1+v)}{\rm d}v\\
&=C+(1-\nu)\chi_3\left(\frac{1-\nu}{1+\nu}\right)-\frac{7\zeta(3)}{8}
-\left.{\color{white}{\frac{1}{1}}}2\chi_2(v)\ln(1+v)\right|^\frac{1-\nu}{1+\nu}
_1+\int^\frac{1-\nu}{1+\nu}_1\frac{\ln(1+v)\ln\left(\frac{1+v}{1-v}\right)}{v}{
\rm d}v\\
&=C+(1-\nu)\chi_3\left(\frac{1-\nu}{1+\nu}\right)-\frac{7\zeta(3)}{8}
+2\chi_2\left(\frac{1-\nu}{1+\nu}\right)\ln\left(\frac{1+\nu}{2}\right)+\frac{
\pi^2}{4}\ln{2}\\
&\ \ \ \
+\frac{1}{2}\int^\frac{1-\nu}{1+\nu}_1\frac{
\ln^2(1+v)-\ln^2(1-v)+\ln^2\left(\frac{1-v}{1+v}\right)}{v}{\rm d}v
\end{align*}
```

**Comment by pkra** [comment]
@zorkow should I rather file this at SRE?

**Comment by zorkow** [comment]
Yes, that is enrichment/SRE related. Must be a regression.

**Comment by zorkow** [comment]
There was a problem with inner structure in embellished fences. The patch to SRE solves this.

**Comment by pkra** [comment]
Thanks. The processing error is fixed but now the collapse extension is broken (see the second collapse on the third line).
 
![respeq](https://cloud.githubusercontent.com/assets/426686/11680100/3ded46f8-9e56-11e5-9266-434fb17fc848.png)

**Comment by zorkow** [comment]
The semantic tree and the embedding in this example are correct, however. It seems to be a problem when collapsing an punctuated/endpunct element.
Here's a minimised version of the example:
\left.a+b+c+d+e\right|^x_y

**Comment by pkra** [comment]
>  It seems to be a problem when collapsing an punctuated/endpunct element.

Right. Should I open a separate issue?

> Here's a minimised version of the example:

Thanks! Confirmed.

It looks like a problem of the HTML-CSS output.

**Comment by pkra** [comment]
I've opened https://github.com/mathjax/MathJax/issues/1332 upstream.

I'm leaving this open to discuss one small detail, I'm curious about: why does one of the `|` not get `fence` and `stretchy` added? (It's from the collapse extension, not enrichment I think.)

**Comment by dpvc** [comment]
> I'm curious about: why does one of the | not get `fence` and `stretchy` added?

Because these are the defaults for the `|` character, so they are removed by the `toMathML()` call that is used to generate the MathML that is passed to the enrichment (since the internal format came from TeX rather than MathML originally, `toMathML()` strips any default attributes).

**Comment by pkra** [comment]
Thanks, Davide.
