### ISSUE TITLE
Make SRE work on both http and https

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#46]
It seems SRE now forces HTTPS, in particular even loading it over http leads to SRE loading its json data via https.

This leads to problems on WinXP (which doesn't support recent encryption cyphers).

A simple way to grab a copy of all relevant files for local testing would be enough.

**Comment by zorkow** [comment]
I've pushed a new version of SRE. @pkra if you find time, ptal.

**Comment by pkra** [comment]
LGTM. Test on WinXP+Chrome worked well.

**Comment by zorkow** [comment]
Closed in https://github.com/zorkow/speech-rule-engine/pull/34
