### ISSUE TITLE
Win7, IE10 speech garbled

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#51]
Looks like the old xpath issues are back again. Was anything changed?

**Comment by pkra** [comment]
It looks as if the subexressions innerText (from MathJax rendering) is injected into the live region. But I don't remember what the old bug looked like exactly.

**Comment by zorkow** [comment]
That could be a problem with the http vs https.

**Comment by pkra** [comment]
Oh, you mean components not making it? I'll check.

**Comment by pkra** [comment]
Indeed. Something goes wrong in SRE.

URL	Method	Result	Type	Received	Taken	Initiator	Wait‎‎	Start‎‎	Request‎‎	Response‎‎	Cache read‎‎	Gap‎‎
/MathJax-RespEq/Semantics-Lab/walker/progressiveaccess.com/content/wgxpath.install.js	GET	404	text/html	0.57 KB	203 ms	<script>	203	63	140	0	0	3266

**Comment by zorkow** [comment]
Can you please try again. It should work now.

**Comment by pkra** [comment]
Yay, fixed.
