### ISSUE TITLE
[a11y tool] only add one initial announcement

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#62]
It seems in documents with more than one equation, the walker is adding an announcement ("nav. math in page, explore with shift+space") for *each* equation, leading to as many announcements as there are equations in the page -- that's a bit annoying :wink:

**Comment by zorkow** [comment]
I can't see that. Where does that happen?

**Comment by zorkow** [comment]
@pkra This should help.

**Comment by zorkow** [comment]
Fixed in #74

**Comment by pkra** [comment]
:+1:
