### ISSUE TITLE
[a11y walker] can't disable assistiveMML nor use inline configurations

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#64]
Something I noticed without time to look into. Due to the bug in 2.6.0 (fixed in 2.6.1), we can't use combined configurations while disabling the AssistiveMML extension. Yet when I switched to just inline configurations, I got Math Processing errors. Probably just a timing issue.

**Comment by dpvc** [comment]
Can you point out which lab or example where you are seeing this problem?  If it is your own code, can you post it?

**Comment by dpvc** [comment]
PS, I use the unpacked version successfully in the Labs and Struik files.

**Comment by pkra** [comment]
I'll look into it.

**Comment by zorkow** [comment]
This should not happen anymore. Close?

**Comment by dpvc** [comment]
Yes.  I'll close.
