### ISSUE TITLE
[a11y walker] improving UX for documents / AT reading modes

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#67]
As an AT user, I want to read documents with mathematics the same way I read other documents, using my AT's smart modes, e.g., to read the entire document or read it line-by-line.

This experience falls short because, e.g., NVDA will (sensibly) read the aria-label ("math") when reading line-by-line, i.e., "When math holds, we get math which implies math". 

While some navigation is availabe to reach back (ctrl+tab to go to previous focusable), it is not always reliable (jumping too far behind). Also, once you're on the focused element, I couldn't figure out if there's a way to get back into the flow.

Some ideas.

* talk to AT community on expected / best-of-class behavior.
* add complete speech text as aria-label (preceded by "math", perhaps, just like headings are preceded by "heading level n")
* consider if we could/should/would get AT to stop at each equation (treating them as newlines, even inline math), and enable smooth UX for activating and continuing(/skipping) the walker.

What else could we do?

**Comment by zorkow** [comment]
The into-struik branch contains a version where the math speech is pushed into the aria-label.
At least ChromeVox stops after a certain number of characters.
Maybe we could put the shortened text in there.

**Comment by zorkow** [comment]
This is  addressed in PR #92 
Labels contain summaries.
