### ISSUE TITLE
Links on README

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-RespEq#89]
Give them names for usability.
(Suggested by Sina.)

**Comment by zorkow** [comment]
I've got some more inquiries regarding the demonstrators. 
I would like to fix these links first: How do we want to name the websites?

**Comment by pkra** [comment]
I don't have any suggestions. The bigger question is how we actually names our products.

**Comment by zorkow** [comment]
True, because people confuse this extension with the assistive mml.

**Comment by pkra** [comment]
> True, because people confuse this extension with the assistive mml.

imo, not really. AssistiveMML is established and can't change until 3.0, so we need a new name.

**Comment by zorkow** [comment]
I did not suggest to rename AssistiveMML. (It's a bit of a of a misnomer in my opinion, as it only exposes MML.) 
We could call it ATE  (Assistive Technology Extension).
Or ASE (Accessibility Support Extension).

**Comment by pkra** [comment]
> I did not suggest to rename AssistiveMML. 

Thanks for clarifying. I had misunderstood you.

> We could call it ATE (Assistive Technology Extension).
> Or ASE (Accessibility Support Extension).

How many extensions will we provide? Should they have different names or, if they are one extension, how should we name the individual features (enrichment, responsive rendering, speech-text, exploration, anything else?).

**Comment by zorkow** [comment]
Good point. I believe that a single extension is sufficient, with separated into the three modules corresponding to the code modules (I guess Semantic-Complexity alone does not make sense).
And then a bunch of config options, pretty much as we have it now in the Accessibility submenu. 
Default should be no speech as it is expensive.

**Comment by pkra** [comment]
@dpvc any thoughts?

**Comment by zorkow** [comment]
I've dressed the raw links now.

**Comment by dpvc** [comment]
These look good.  Sorry for letting the RFC slip past me.
