### ISSUE TITLE
Problem with annotation element.

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-RespEq#98]
If a MathML semantics annotation element (apparently Mathtype adds those) stops rendering of the enriched expression.
Simple example:

```
<math><semantics><mrow><mi>a</mi><mi>b</mi></mrow><annotation>implicit times</annotation></semantics></math>
```

**Comment by zorkow** [comment]
@dpvc I've tested that a bit and it does not seem to have anything to do with the explorer. 
E.g., when you take out the assistive-explore extension entirely, it still does not render.
The enriched MathML looks correct, though.

**Comment by dpvc** [comment]
It is in the Semantic-Collapse code.  I just pushed a fix for it in the `issue98` branch.  I'll make a PR.
